### ISSUE TITLE
Check and Change

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-examples#35]
This is already [here](https://github.com/alphagov/govuk-design-system-backlog/issues/36) but thought it would be good to open up a discussion here to see what we have.

I know @Ash-Wilson already shared one so I will use that as a base.

## Screenshot

![45158583-4bf3f200-b1dc-11e8-85dd-1512d8f43b34](https://user-images.githubusercontent.com/4334015/50146896-ba9d1d00-02ac-11e9-97c5-6c1736858a47.png)

## What problem does this design solve?

I think there is a split of need here about the check and the change.

Check, my assumption is that people need to validate the information they have supplied, specially over multiple part forms, be good to sure that assumption up though.

The change element, I've not seen any data around how much it is used and clear needs around it.

The example above doesn't work well in a one thing per page situation, so it would be good to work that out.

**Comment by htmlandbacon** [comment]
This is also different to the [prototype kit version](https://govuk-prototype-kit.herokuapp.com/docs/templates/check-your-answers)

**Comment by Ash-Wilson** [comment]
@htmlandbacon the prototype kit version didn't work for our users because we've not used the one thing per page as simply as that. We have stuck to it but sort of grouped items, for example 'Tenant Details' as you can see above. I know @abbott567 also did some work with this but then changed it back to the original.

I think there is a definite user need for another option where the user can review and change (check and change - whatever the terminology may end up being) and agree this is a split need.

This version is currently in private beta and i've had positive feedback. But there is the same observations as in the past where users only skim read. 

Happy to discuss this and glad we are considering it :)

**Comment by abbott567** [comment]
We had the same issue as Ash. The GDS pattern has a table row and a change link for each one. This works well for one thing per page. But we use 'one theme per page'. So Claimant Details will include everything about the claimant. Eg, Name, NINO, Date of birth etc. So there was essentially 3 or 4 change links all going to the same place. User research kept showing that this was pointless and confusing for the agents using the service.

So, we did originally move the change link to the top so it was in line with the title, like in Colin's original post. This works well for us and in out MVP this is the design that was implemented in production. 

However, when we came to integrate with CIS we needed a way to show the agent whether the details were verified or not. Because they already use Searchlight, it made sense just to steal the verified icon from Searchlight so it would already feel familiar. I couldn't really find anywhere to put the verified icon, so it ended up taking the space where the change link had been moved to, and I moved the change link to be centred vertically. This also meant removing the grid lines so it was obvious the change link was not restricted to a single row, but anything in the block.

Again, this design is testing really well and is in the production version of claim manager now. We've got the change links tagged with GA, so I've asked for a pull on the stats but I won't have them probably 'til early 2019 now as everyone is wrapping up for Christmas (no pun intended). 

Here's a screenshot of the design we are using at the moment:
![image](https://user-images.githubusercontent.com/9450064/50150151-0784f180-02b5-11e9-9969-56ce00f7a47f.png)
